FROM i386/alpine:3.22@sha256:d82a85e22ec68fbe569507f2357edac47621e4b87c4397a08339f8cae93c5e2b
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8080 8081
VOLUME ["/var/lib/redirects"]
ENTRYPOINT ["/usr/bin/redirects"]
CMD ["server"]
HEALTHCHECK CMD /usr/bin/redirects health

COPY bin/redirects /usr/bin/redirects
