FROM arm32v6/alpine:3.21@sha256:e652ca0a0ac7cd8dddc4076009c56599c2dd20d3c394c53c8af176ec6dbd6714
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8080 8081
VOLUME ["/var/lib/redirects"]
ENTRYPOINT ["/usr/bin/redirects"]
CMD ["server"]
HEALTHCHECK CMD /usr/bin/redirects health

COPY bin/redirects /usr/bin/redirects
