FROM i386/alpine:3.20@sha256:ac77ebc035f69184acb2660028580c9053f6d0f892de7933e1456d8b5e0ac085
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8080 8081
VOLUME ["/var/lib/redirects"]
ENTRYPOINT ["/usr/bin/redirects"]
CMD ["server"]
HEALTHCHECK CMD /usr/bin/redirects health

COPY bin/redirects /usr/bin/redirects
