FROM arm32v6/alpine:3.17@sha256:a266c9bd3023933cc83bfe71c969982314e1adf1eb6d1db506833e1e64b8ac4f
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8080 8081
VOLUME ["/var/lib/redirects"]
ENTRYPOINT ["/usr/bin/redirects"]
CMD ["server"]
HEALTHCHECK CMD /usr/bin/redirects health

COPY bin/redirects /usr/bin/redirects
