FROM amd64/alpine:3.22@sha256:f29909b294ed398ae64ad9bc268a3ce2c4824fb37375cac63763e6e8f886f3b1
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8080 8081
VOLUME ["/var/lib/redirects"]
ENTRYPOINT ["/usr/bin/redirects"]
CMD ["server"]
HEALTHCHECK CMD /usr/bin/redirects health

COPY bin/redirects /usr/bin/redirects
